config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'profile' => 'users#profile'

  root to: 'pets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets, only: [:new, :create, :show] do
    resources :bookings, only: [:new, :create]
  end

  patch "/archive_booking/:id", to: 'bookings#archive'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, class_name: 'User'#, counter_cache: true,
  belongs_to :pet
  has_one :owner, through: :pet

  #validates :start_date, :end_date, presence: true, availability: true
  #validate :end_date_after_start_date

  def booked_date_range
    { from: :start_date, to: :end_date }
  end

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "doit être après la date de début")
    end
 end
end

#class Booking < ApplicationRecord
#  belongs_to :customer, class_name: 'User'
#  belongs_to :pet
#  has_one :owner, through: :pet
#end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :bookings
  has_many :customers, -> { distinct }, through: :bookings
  has_many_attached :photos

  #def unavailable_dates
  #  bookings.pluck(:start_date, :end_date).map do |range|
  #    { from: range[0], to: range[1] }
  #  end
  #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :own_pets, foreign_key: 'owner_id', class_name: 'Pet'
  has_many :owner_bookings, through: :own_pets, source: :bookings
  has_many :customer_bookings, foreign_key: 'customer_id', class_name: 'Booking'
  has_many :customer_pets, -> { distinct }, through: :customer_bookings, source: :pet
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :decription, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    # A FAIRE POUR L'UPDATE D'UN USER
    # devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new(booking_params)
    @booking.pet = @pet
    @booking.customer = current_user
    if @booking.save
      redirect_to pet_path @pet
    else
      render 'pet/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:show]
  skip_before_action :authenticate_user!, only: :index

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
    @is_owner = current_user.own_pets.length > 0 ? true : false
    @booking = Booking.new
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.owner = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  # def edit
  # end

  # def update
  #   if @pet.update(pet_params)
  #     redirect_to @pet
  #   else
  #     render :edit
  #   end
  # end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :category, :description, :pricing, photos: [])
  end

  def find_pet
    @pet = Pet.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_user
  before_action :set_photo, only: [:show, :destroy]

  # GET /users/1/photos
  def index
  end

  # GET /users/1/photos/abc
  def show
    @downloaded = @photo.download
  end

  # DELETE /users/1/photos/abc
  def destroy
    @photo.purge
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Votre photo a été correctement supprimée.' }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_photo
    @photo = @user.photos.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def profile # = show
    @owner = !current_user.own_pets.empty?
  end

  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'profile correctement créé.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'profile correctement mis à jour.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'profile correctement supprimé.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :description, :avatar, :photos)
  end

  def article_params
    params.require(:user).permit(:name, :description, :photo)
    params.require(:user).permit(:name, :decription, :photo)
  end

  def find_pet
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@pet, @booking]) do |f| %>
  <div class="dates">
    <div class="form-inputs">
      <div class="form-row">
        <%= f.input :start_date, as: :string, label: "Merci de choisir un jour :", placeholder: "JJ/MM/YYYY", wrapper_html: { class: "inline_field_wrapper" } %>
      </div>
    </div>
  </div><br>
  <div class="form-row">
    <%= f.submit "Je veux #{@pet.name}!" , class: "btn btn-flat"  %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="form-group">
  <label for="date">Choisir une journée</label>
  <input type="date" id="date" placeholder="DD/MM/YYYY" class="form-control">

  <%= f.submit %>
</div>

app/views/bookings/new.thml.erb
<div class="form-group">
  <label for="date">Choisir une journée</label>
  <input type="date" id="date" placeholder="DD/MM/YYYY" class="form-control">

  <%= f.submit %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetMyPet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.typekit.net/zpr8ueq.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h1>Bonjour <%= current_user.name %>, </h1>
      <%= simple_form_for(@pet) do |f| %>
        <%= f.input :name %>
        <%= f.input :age %>
        <%= f.input :category %>
        <%= f.input :description %>
        <%= f.input :pricing %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <input class="btn btn-flat" type="submit" name="submit"/>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/index.html.erb
<div class="container">
  <div class="text-date">
      <label for="date"><p class="p-small"><strong>Besoin d'amour ? Louez un pet pour un jour !</strong></p></label>
    <div class="form-group">
      <input type="date" id="date" placeholder="DD/MM/YYYY" class="form-control">
    </div>
  </div>
  <div class="row">
    <div class="container-card"></div>
      <% @pets.each do |pet| %>
        <div class="col-lg-4 mb-4">
          <div class="card-pet">
            <div class="card-pet-image">
              <% pet.photos.each do |photo| %>
                <%= cl_image_tag photo.key, class: "image-size"%>
              <% end %>
            </div>

            <div class="card-pet-content">
              <h3><%= link_to pet.name, pet %></h3>
              <div class="card-pet-content-pricing">
                <i class="fas fa-bone"></i>
                <p><strong><%= pet.pricing %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
   </div>
 </div>
</div>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-8">
          <div class="col-md-12">
              <h1>Bonjour, je suis <%= @pet.name %> !</h1><br>
              <% @pet.photos.each do |photo| %>
                <%= cl_image_tag photo.key, height: 360, width: 460, crop: :fill, class:"image-show" %>
              <% end %>
              <div class="pet-details">
                <p>j'ai <%= @pet.age %> ans, je suis un <%= @pet.category %></p>
                <p>, et j'ai besoin de <strong><%= @pet.pricing %></strong></p>
                <span>&nbsp&nbsp</span>
                <i class="fas fa-bone"></i>
              </div>
              <%= @pet.description %>
              <div><br>
                <% if @is_owner %>
                <p>Je suis l'animal de <strong><%= @pet.owner.name %></strong></p>
                <% end %>
              </div>

          </div>
      </div>
      <div class="col-md-4">
        <div class="date">
          <%= render "bookings/form" %>
        </div>
      </div>
  </div>
</div>

app/views/photos/index.html.erb
<h3>Mes Photos</h3>
<% @user.photos.each do |photo| %>
  <%= cl_image_tag(photo.key, width: 100, height: 100, gravity: :auto, crop: :thumb, fetch_format: :auto) %>
<% end %>
<%= form_with(model: @user, remote: true) do |form| %>
  <p>
    <%= form.label :photos, "Upload New Photos (direct upload):" %>
    <%= form.file_field :photos, multiple: true, direct_upload: true %>
  </p>

  <%- # Lets the action not error out if they haven't attached a file, since user param will be present %>
  <%= form.hidden_field :hello %>
  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>
<%= link_to 'Back', user_path(@user) %>

app/views/photos/show.html.erb
<p>
  Downloaded the image to check size!
</p>
<p>
  Image size in bytes: <%= @downloaded.bytesize %>
</p>
<p>
  Attempting to display image (from memory, not from Cloudinary; this only works if it's a compatible image type):
</p>
<p>
  <img src="data:<%= @photo.key.attributes[:content_type] %>;base64, <%= Base64.encode64(@downloaded) %>">
</p>
<%= link_to 'Back', user_path(@user) %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="navbar-logo">
      <%= image_tag "logo.png" %>
      <h2>Pet My Pet</h2>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active" >
        <% if current_user != nil %>
          <%= link_to "#{current_user.name}", profile_path , class: "nav-link" %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mon profil", profile_path, class: "dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <%= link_to "sign in !", new_user_session_path , class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: current_user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Profile Photo" %>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Modifier son profile</h1>

<%= render 'form', user: @user %>
<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>
<%= link_to 'Back', users_path %>

app/views/users/profile.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-8">
          <div class="col-md-12">
              <h1>Bonjour, je suis <%= current_user.name %> !</h1><br>
              <%= current_user.decription %>
          </div>
      </div>

      <div class="col-md-4">
        <div class="col-md-12">
          <%= link_to "Add a pet !", new_pet_path , class: "btn btn-flat" %>
        </div><br>
        <div>
          <% if @owner %>
            <strong><%= "Je suis l'heureux propriétaire de :" %></strong>
            <div><br>
              <% @current_user.own_pets.each do |pet| %>
                <p><%= link_to pet.name, pet_path(pet) %></p>÷/
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div>
   <p>
    <%= cl_image_tag(@current_user.avatar.key, height: 50, width: 50, gravity: :face, crop: :thumb, sign_url: true) %>
    <strong><%= @current_user.name %></strong>
  </p>
  <%= link_to 'Edit My Profile', edit_current_user_path(@user) %>
</div>

<p>
  <strong>Mes Photos:</strong>
  <% @current_user.photos.each do |photo| %>
    <div style="display: inline-block; width: 200">
      <%= link_to(cl_image_tag(photo.key, height: 200, width: 200, gravity: :auto, crop: :thumb, sign_url: true, fetch_format: :auto), url_for(photo)) %>
      <p style="text-align: center;">
        <%= link_to 'Image Info', current_user_photo_path(@current_user, photo) %>
        <%= link_to 'Delete Image', current_user_photo_path(@current_user, photo), method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    </div>
  <% end %>
</p>

<%= form_with(model: @user, local: true) do |form| %>
  <p>
    <%= form.label :photos, "Upload New Photos:" %>
    <%= form.file_field :photos, multiple: true %>
  </p>

  <%- # Lets the action not error out if they haven't attached a file, since user param will be present %>
  <%= form.hidden_field :hello %>
  <div class="actions">
    <%= form.submit "Upload" %>
  </div>
<% end %>
<%= link_to 'Direct Upload Demo', current_user_photos_path(@user) %> |
<%= link_to 'Back', current_users_path %>